Algoritmo "Exercicio49"
// Disciplina: [Linguagem e Lógica de Programação]
// Professor:Jailson
// Descrição:Contador de 1 até 10 usando o para
// Autor(a): Maiara
// Data atual:21/03/23
Var
// Seção de Declarações das variáveis
indice: inteiro



Inicio

para indice de 1 ate 10 faca
escreva (indice)
fimpara
Fimalgoritmo






































