Algoritmo "Exercicio52"
// Disciplina: [Linguagem e Lógica de Programação]
// Professor:Jailson
// Descrição:Contador de 101 até 110
// Autor(a): Maiara
// Data atual:21/03/23
Var
// Seção de Declarações das variáveis
indice: inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para indice de 101 ate 110 faca
escreva (indice)
fimpara
Fimalgoritmo








































