Algoritmo "Exercicio12"
// Disciplina: [Linguagem e Lógica de Programação]
// Professor:Jailson
// Descrição:Converte Fahrenheit para celsius
// Autor(a): Maiara
// Data atual:15/03/23
Var
// Seção de Declarações das variáveis
Fahrenheit:real
calculo:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Temperatura em Fahrenheit")
leia (Fahrenheit)
calculo <- (Fahrenheit-32)*5/9
escreva ("Celsius: ", calculo)

Fimalgoritmo
